name: samd-ss
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.26.*
  - scipy=1.11.*
  - scikit-learn=1.4.*
  - matplotlib=3.8.*
  - pandas=2.2.*
  - numba=0.58.*
  - jupyterlab=4.2.*
  - notebook=7.2.*
  - ipywidgets=8.1.*
  - seaborn=0.13.*
  - pytest=8.3.*
  - pyyaml=6.0.*
  - tqdm=4.66.*
  - rich=13.7.*
  - psutil=5.9.*
  - pip
  - pip:
      - nbformat==5.10.4
      - nbclient==0.9.0
      - papermill==2.6.0
